const products = [
  {
    _id: "1",
    url: "https://www.aiiz.com/Product/AW19/Women/YH1DTL-BCIB01NV_IMG1.jpg",
    name: "เสื้อคอจีนแขนยาวผู้หญิง พิมพ์ลาย ผ้าเรยอน",
    brand: "AIIZ",
    price: 490,
    stars: 5.0,
  },
  {
    _id: "2",
    url: "https://www.aiiz.com/Product/SS20/Men/MJ1PTD-CCSB02RE_IMG1.jpg",
    name: "เสื้อแจ็คเก็ตกันลม",
    brand: "A2Z",
    price: 745,
    stars: 4.0,
  },
  {
    _id: "3",
    url: "https://www.aiiz.com/Product/SS20/Men/MF1ATR-CCSW01NV_IMG1.jpg",
    name: "เสื้อสเวตเตอร์คอกลมผู้ชาย ผ้าแฟลตนิต ลายริ้วคาดอก",
    brand: "Atwoz",
    price: 379,
    stars: 4.2,
  },
  {
    _id: "4",
    url: "https://www.aiiz.com/Product/SS19/Girls/GP5PBP-B3CW01TD_IMG1.jpg",
    name: "กางเกงขาสั้นเด็กผู้หญิง เอวยางยืด",
    brand: "Atuz",
    price: 239,
    stars: 4.5,
  },
  {
    _id: "5",
    url: "https://www.aiiz.com/Product/SS20/Girls/GP5PBS-CBCI01DB_IMG1.jpg",
    name: "กางเกงขาสั้นเด็กผู้หญิง แต่งระบาย",
    brand: "atruez",
    price: 290,
    stars: 4.1,
  },
  {
    _id: "6",
    url: "https://www.aiiz.com/Product/SS20/Girls/GQICIX-C8HX02NV_IMG1.jpg",
    name: "พรีเมี่ยม ทรีดี แมส มีสายคล้องคอ สำหรับเด็กอายุ 4-12 ปี(สีน้ำเงิน)",
    brand: "AtoruZ",
    price: 110,
    stars: 4.0,
  },
  {
    _id: "7",
    url: "https://www.aiiz.com/Product/SS20/Girls/GQICIX-C6HX03WH_IMG1.jpg",
    name: "พรีเมี่ยม ทรีดี แมส สำหรับเด็กอายุ 4-12 ปี",
    brand: "Nike",
    price: 110,
    stars: 4.0,
  },
  {
    _id: "8",
    url: "https://www.aiiz.com/Product/SS20/Women/YQIPIM-CCHW01NV_IMG1.jpg",
    name: "ผ้าห่ม สีพื้น ขนาดใหญ่",
    brand: "ATTz",
    price: 60,
    stars: 4.51,
  },
];

export default products;
