const products =  [
    {
      _id: "1",
      url: "https://www.aiiz.com/Product/AW19/Women/YH1DTL-BCIB01NV_IMG1.jpg",
      name: "เสื้อคอจีนแขนยาวผู้หญิง พิมพ์ลาย ผ้าเรยอน",
      brand: "AIIZ",
      price: 490 ,
      stars: 5,
    },
    {
      _id: "2",
      url: "https://picsum.photos/id/401/800/600",
      name: "shirt",
      brand: "dragonfly",
      price: 160,
      stars: 5,
    },
    {
      _id: "3",
      url: "https://picsum.photos/id/502/800/600",
      name: "Slim Pants",
      brand: "Jackma",
      price: 160,
      stars: 4.0,
    },
    {
      _id: "4",
      url: "https://picsum.photos/id/1010/800/600",
      name: "Slim Shirt",
      brand: "Nike",
      price: 60,
      stars: 4.5,
    },
    {
      _id: "5",
      url: "https://picsum.photos/id/1000/800/600",
      name: "Slim Shirt",
      brand: "Nike",
      price: 60,
      stars: 4.5,
    },
    {
      _id: "6",
      url: "https://picsum.photos/id/912/800/600",
      name: "Slim Shirt",
      brand: "Nike",
      price: 60,
      stars: 4.5,
    },
    {
      _id: "7",
      url: "https://picsum.photos/id/1012/800/600",
      name: "Slim Shirt",
      brand: "Nike",
      price: 60,
      stars: 4.5,
    },
    {
      _id: "8",
      url: "https://picsum.photos/800/600",
      name: "Slim Shirt",
      brand: "Nike",
      price: 60,
      stars: 4.5,
    },
  ];

export default products;
